<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Panda Login</title>  
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <!--<script src="/js/index.js"></script>--> 
        <link rel="stylesheet" href="/css/style.css"> 
</head>

<body>
    <div class="panda">
        <div class="ear"></div>
        <div class="face">
            <div class="eye-shade"></div>
            <div class="eye-white">
                <div class="eye-ball"></div>
            </div>
            <div class="eye-shade rgt"></div>
            <div class="eye-white rgt">
                <div class="eye-ball"></div>
            </div>
            <div class="nose"></div>
            <div class="mouth"></div>
        </div>
    <div class="body"> </div>
    <div class="foot">
        <div class="finger"></div>
    </div>
    <div class="foot rgt">
        <div class="finger"></div>
    </div>
    </div>
    <form action="/auth/index/login" method="post">
        <div class="hand"></div>
        <div class="hand rgt"></div>
        <h1>Form Login</h1>
        <div class="form-group">
            <input name= "username" required="required" class="form-control"/>
            <label class="form-label">Username </label>
        </div>
        <div class="form-group">
            <input id="password" name="password" type="password" required="required" class="form-control"/>
            <label class="form-label">Password</label>
        </div>
            <div id="remember" class="checkbox" style="margin-top: 20px;">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            </div>
            <div class="from-group" style="margin-bottom: 10px;">
                <button class="btn">Login </button>
            </div> 
            <a href="#" >Forgot Password</a>
    </form>
</body>
</html>
